---
- hosts: webservers
  become: yes
  tasks:
    - name: Install Python and pip
      win_chocolatey:
        name: python
        version: 3.8.0
        state: present

    - name: Install Docker
      win_chocolatey:
        name: docker-desktop
        state: present