version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
  prometheus:
    image: prom/prometheus
    ports:
      - "9091:9090"
    # volumes:
    #   - ./app/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.y
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-storage: