pipeline {
    agent any

    options {
        timestamps() // Optional: Adds timestamps to console output
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/HarshaDoda/devops-cicd-project.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'docker-compose -f app/docker-compose.yml build'
            }
        }

        stage('Run Tests') {
            steps {
                bat 'docker-compose -f app/docker-compose.yml run --rm web python -m pytest tests/'
            }
        }

        stage('Code Quality Scan') {
            steps {
                // Uncomment and configure your SonarQube env if needed
                // withSonarQubeEnv('sonarqube') {
                //     bat 'sonar-scanner'
                // }
                echo 'Code quality analysis placeholder'
            }
        }

        stage('Push to DockerHub') {
            steps {
                script {
                    withCredentials([usernamePassword(
                        credentialsId: 'dockerhub-creds',
                        usernameVariable: 'DOCKER_HUB_USR',
                        passwordVariable: 'DOCKER_HUB_PSW'
                    )]) {
                        bat '''
                         echo %DOCKER_HUB_PSW% | docker login -u %DOCKER_HUB_USR% --password-stdin
                         docker tag devops-cicd-project_web:latest %DOCKER_HUB_USR%/myapp:latest
                         docker push %DOCKER_HUB_USR%/myapp:latest
                        '''
                    }
                }
            }
        }

        stage('Deploy Locally') {
            steps {
                bat 'docker-compose up -d'
            }
        }
    }

    // post {
    //     success {
    //         slackSend(color: 'good', message: "✅ Build #${BUILD_NUMBER} succeeded!")
    //     }
    //     failure {
    //         slackSend(color: 'danger', message: "❌ Build #${BUILD_NUMBER} failed!")
    //     }
    // }
}
